<?php include VIEWS.'header.phtml'; ?>
<br>
    <div class="container">
        <nav class="navbar navbar-default">
            <div class="container-fluid">
            
            </div>
        </nav>
        <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-4">
                <div class="panel panel-default">
                    <div class="panel-heading">Login</div>
                    <div class="panel-body">
                    <form action="tryLogin" method="post">
                        <div class="form-group">
                            <label for="name">Name:</label>
                            <input type="text" class="form-control" name="name" id="name" value="">
                        </div>
                        <div class="form-group">
                            <label for="password">Password:</label>
                            <input type="password" class="form-control" name="password" id="password" value="">
                        </div>
                        <input class="btn btn-default" type="submit" value="Login">
                    </form>
                    </div>
                </div>
            </div>
            <div class="col-md-4"></div>
        </div>
    </div>
<?php include VIEWS.'footer.phtml'; ?>