<?php include VIEWS.'header.phtml'; ?>

<br>
<div class="container">
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">Error...</div>
                <div class="panel-body">
                    <p><?php echo $parameters['message'] ?></p>
                </div>
            </div>
        <div>
        <div class="col-md-4"></div>
    </div>
</div>

<?php include VIEWS.'footer.phtml'; ?>