<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="A web application done for testing purposes">
    <meta name="author" content="Alejandro Lopez">
    <link rel="icon" href="favicon.ico" type="image/ico">
    <title>ABC Hosting Test</title>
    <link href="/online-shop-abc.zz.com.ve/public/assets/bootstrap-3.3.7-dist/css/bootstrap.css" rel="stylesheet">
  </head>
  <body>
