<?php include VIEWS . 'header.phtml'; ?>
<br>
<div class="container">
        <nav class="navbar navbar-default">
            <div class="container-fluid">
            <?php
            if(!empty($_SESSION['loggedUser']))
            {
                echo "<button type='button' class='btn btn-default navbar-btn navbar-left' onclick='window.location.href=\"../../products/read\"'><span class='glyphicon glyphicon-tag'></span></button>";
                echo "<p class='navbar-text'>Signed in as ".$_SESSION['loggedUser']->name."</p>";
                echo "<button type='button' class='btn btn-default navbar-btn navbar-right' onclick='window.location.href=\"../log/logout\"'>Log out</button>";
            }
            else
            {
                echo "<button type='button' class='btn btn-default navbar-btn navbar-right' onclick='window.location.href=\"../log/login\"'>Log in</button>";
            }
            ?>
            </div>
        </nav>
        <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-4">
                <div class="panel panel-default">
                    <div class="panel-heading">Add a product to your shopping cart...</div>
                    <div class="panel-body">
                    <form action="../saveCreate" method="post">
                    <div class="form-group">
                            <label for="id" hidden>Id:</label>
                            <input type="text" class="form-control hidden" name="id" id="id" value="<?php echo $parameters['product'][0]->id; ?>" readonly>
                        </div>
                        <div class="form-group">
                            <label for="name">Name:</label>
                            <input type="text" class="form-control" name="name" id="name" value="<?php echo $parameters['product'][0]->name; ?>" readonly>
                        </div>
                        <div class="form-group">
                            <label for="price">Price:</label>
                            <input type="text" class="form-control" name="price" id="price" value="<?php echo $parameters['product'][0]->price; ?>"readonly>
                        </div>
                        <div class="form-group">
                            <label for="units">Units:</label>
                            <input class="form-control" type="number" name="units" id="units" min="1" value="1">
                        </div>
                        <input class="btn btn-default" type="submit" value="Add">
                    </form>
                    </div>
                </div>
            </div>
            <div class="col-md-4"></div>
        </div>
    </div>
<?php include VIEWS . 'footer.phtml'; ?>