<?php include VIEWS . 'header.phtml'; ?>
<script>history.pushState(null, '', '/shoppingCart/read');    </script>
<br>
<div class="container">
    <nav class="navbar navbar-default">
        <div class="container-fluid">
        <?php
        if(!empty($_SESSION['loggedUser']))
        {
            echo "<button type='button' class='btn btn-default navbar-btn navbar-left' onclick='window.location.href=\"../products/read\"'><span class='glyphicon glyphicon-tag'></span></button>";
            echo "<p class='navbar-text'>Signed in as ".$_SESSION['loggedUser']->name." with a balance of <b>".$_SESSION['loggedUser']->balance."$</b></p>";
            echo "<button type='button' class='btn btn-default navbar-btn navbar-right' onclick='window.location.href=\"../log/logout\"'>Log out</button>";
        }
        else
        {
            echo "<button type='button' class='btn btn-default navbar-btn navbar-right' onclick='window.location.href=\"../log/login\"'>Log in</button>";
        }
        ?>
        </div>
    </nav>
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading">Shopping Cart</div>
                <table class="table">
                    <thead>
                    <tr>
                        <th>Product</th>
                        <th>Unit(s)</th>
                        <th>Price</th>
                        <th>Actions</th>
                        <th>Total</th>
                    </tr>
                    </thead>
                    <tbody>
                        <?php foreach($parameters['products'] as $product) : ?>
                        <tr>
                            <td><?php echo $product->name; ?></td>
                            <td><?php echo $product->units; ?></td>
                            <td><?php echo "$".$product->price; ?></td>
                            <td>
                                <button type="button" class="btn btn-default" onclick="window.location.href = 'delete/<?php echo $product->id; ?>'">
                                    <span class="glyphicon glyphicon-minus-sign"></span>
                                </button>
                            </td>
                            <td><?php $total=0; $total=$product->price * $product->units; echo "$".$total ?></td>
                        </tr>
                        <?php endforeach; ?>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>
                            <?php
                            $grandTotal = 0;
                            foreach($parameters['products'] as $product) {$grandTotal = $grandTotal + ($product->price * $product->units);}
                            echo "$<b>".$grandTotal."</b>";
                            ?>
                        </td>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="col-md-3">
            <div class="panel panel-default">
                <div class="panel-heading">
                <form role="form" action="pay" method="post">
                        <label>Shipping Options</label>
                    <div class="radio">
                        <label>
                        <input type="radio" name="optionsRadios" required> Pick up (free)
                        </label>
                    </div>
                    <div class="radio">
                        <label>
                        <input type="radio" name="optionsRadios" required> UPS ($5)
                        </label>
                    </div>
                    <input type="text" name="grandTotal" value="<?php echo $grandTotal; ?>" hidden>
                    <button type="submit" class="btn btn-success">Pay</button>
                </form>
                </div>
            </div>
        </div>
    </div>
</div>

<?php include VIEWS . 'footer.phtml'; ?>