<?php include VIEWS . 'header.phtml'; ?>
    <br>
    <div class="container">

        <nav class="navbar navbar-default">
            <div class="container-fluid">
            <button type="button" class="btn btn-default navbar-btn navbar-right" onclick="window.location.href = '../login';">Sign in</button>
            </div>
        </nav>

        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">Products</div>
                    <table class="table">
                        <thead>
                        <tr>
                            <th>Name</th>
                            <th>Price</th>
                            <th>Rating</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                            <?php foreach($parameters['products'] as $product) : ?>
                            <tr>
                                <td><?php echo $product->name ?></td>
                                <td><?php echo $product->price ?></td>
                                <td><?php echo $product->rating ?></td>
                                <td>
                                    <button type="button" class="btn btn-default" onclick="window.location.href = 'update/<?php echo $product->id ?>';">
                                        <span class="glyphicon glyphicon-edit">
                                    </button>
                                    <button type="button" class="btn btn-default" onclick="window.location.href = 'delete/<?php echo $product->id ?>';">
                                        <span class="glyphicon glyphicon-minus-sign">
                                    </button>
                                    <button type="button" class="btn btn-default" onclick="window.location.href = 'delete/<?php echo $product->id ?>';">
                                        <span class="glyphicon glyphicon-shopping-cart">
                                    </button>
                                </td>
                            </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
                <button type="button" class="btn btn-default" onclick="window.location.href = 'create';">
                    <span class="glyphicon glyphicon-plus-sign">
            </div>
        </div>
    </div>

    <?php include VIEWS . 'footer.phtml'; ?>