<?php include VIEWS . 'header.phtml'; ?>
    <script>history.pushState(null, '', '<?php echo SITE_PATH; ?>/products/read');    </script>
    <br>
    <div class="container">

    <?php
        /* if(!empty($_SESSION['loggedUser']))
            {
                echo "<div class='masthead'><h3 class='text-muted'>Hello ".$_SESSION['loggedUser']->name."!</h3></div>";
            } */
    ?>
        <nav class="navbar navbar-default">
            <div class="container-fluid">
            <?php
            if(!empty($_SESSION['loggedUser']))
            {
                echo "<button type='button' class='btn btn-default navbar-btn navbar-left' onclick='window.location.href=\"../shoppingCart/read\"'><span class='glyphicon glyphicon-shopping-cart'></span></button>";
                echo "<p class='navbar-text'>Signed in as ".$_SESSION['loggedUser']->name."</p>";
                echo "<button type='button' class='btn btn-default navbar-btn navbar-right' onclick='window.location.href=\"../log/logout\"'>Log out</button>";
            }
            else
            {
                echo "<button type='button' class='btn btn-default navbar-btn navbar-right' onclick='window.location.href=\"../log/login\"'>Log in</button>";
            }
            ?>
            </div>
        </nav>

        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">Products</div>
                    <table class="table">
                        <thead>
                        <tr>
                            <th>Name</th>
                            <th>Price</th>
                            <th>Rating</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                            <?php foreach($parameters['products'] as $product) : ?>
                            <tr>
                                <td><?php echo $product->name ?></td>
                                <td><?php echo $product->price ?></td>
                                <td>
                                    <?php
                                        if(!empty($_SESSION['loggedUser']))
                                        {
                                            foreach($parameters['ratings'] as $rating)
                                            {
                                                if($rating->idProduct == $product->id)
                                                {
                                                    echo $rating->average;
                                                }
                                            }
                                        }
                                    ?>
                                </td>
                                <td>
                                    <?php
                                        if(!empty($_SESSION['loggedUser']))
                                        {
                                            $rated = false;
                                            foreach($parameters['ratings'] as $rating)
                                            {
                                                if($rating->idProduct == $product->id)
                                                {
                                                    $rated = true;
                                                    break;
                                                }
                                                else
                                                {
                                                    $rated = false;
                                                }
                                            }
                                            if($rated)
                                            {
                                                echo "<button type='button' class='btn btn-success btn-sm' onclick='window.location.href = \"thumbsUp/".$product->id."\"' disabled><span class='glyphicon glyphicon-thumbs-up'></span></button>";
                                                echo "<button type='button' class='btn btn-danger btn-sm' onclick='window.location.href = \"thumbsDown/".$product->id."\"' disabled><span class='glyphicon glyphicon-thumbs-down'></span></button>";
                                            }
                                            else
                                            {
                                                echo "<button type='button' class='btn btn-success btn-sm' onclick='window.location.href = \"thumbsUp/".$product->id."\"'><span class='glyphicon glyphicon-thumbs-up'></span></button>";
                                                echo "<button type='button' class='btn btn-danger btn-sm' onclick='window.location.href = \"thumbsDown/".$product->id."\"'><span class='glyphicon glyphicon-thumbs-down'></span></button>";
                                            }
                                        }
                                    ?>
                                    <button type="button" class="btn btn-default" onclick="window.location.href = 'update/<?php echo $product->id; ?>'">
                                        <span class="glyphicon glyphicon-edit"></span>
                                    </button>
                                    <button type="button" class="btn btn-default" onclick="window.location.href = 'delete/<?php echo $product->id; ?>'">
                                        <span class="glyphicon glyphicon-minus-sign"></span>
                                    </button>
                                    <?php
                                    if(!empty($_SESSION['loggedUser']))
                                    {
                                        echo "<button type='button' class='btn btn-default' onclick=\"window.location.href='../shoppingCart/create/".$product->id."';\">";
                                        echo "<span class='glyphicon glyphicon-shopping-cart'></span></button>";
                                    }
                                    ?>
                                </td>
                            </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
                <button type="button" class="btn btn-default" onclick="window.location.href = 'create';">
                    <span class="glyphicon glyphicon-plus-sign"></span>
                </button>
            </div>
        </div>
    </div>

    <?php include VIEWS . 'footer.phtml'; ?>