<?php include VIEWS.'header.phtml'; ?>
<br>
<div class="container">
    <nav class="navbar navbar-default">
        <div class="container-fluid">
        <button type="button" class="btn btn-default navbar-btn navbar-right" onclick="window.location.href = '../login';">Sign in</button>
        </div>
    </nav>
    <div class="jumbotron">
        <h1>Welcome!</h1>
        <p class="lead">This is a online shop made as a test for a job position at ABC Hosting</p>

        <p><a class="btn btn-lg btn-success" href="products/read" role="button">Products List</a></p>
    </div>
</div>
<?php include VIEWS.'footer.phtml'; ?>