<?php include VIEWS . 'header.phtml'; ?>
    <br>
    <div class="container">
        <nav class="navbar navbar-default">
            <div class="container-fluid">
            <button type="button" class="btn btn-default navbar-btn navbar-right" onclick="window.location.href = '../../login';">Sign in</button>
            </div>
        </nav>
        <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-4">
                <div class="panel panel-default">
                    <div class="panel-heading">Please verify before delete...</div>
                        <div class="panel-body">
                            <form action="../saveDelete" method="post">
                                <div class="form-group">
                                    <label for="name">Id:</label>
                                    <input type="text" class="form-control" name="id" id="id" value="<?php echo $parameters['id'] ?>">
                                </div>
                                <input class="btn btn-default" type="submit" value="Delete">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4"></div>
        </div>
    </div>
<?php include VIEWS . 'footer.phtml'; ?>